num_topics: 5
alpha: 0.01
eta: 0.01
chunksize: 200
passes: 40
iterations: 300
offset: 64.0
eval_every: 5
minimum_probability: 0.0
minimum_phi_value: 0.01
per_word_topics: true
random_state: 42
dtype: float32

